export const URL = {
  BASE: 'https://test-team-project-react-nodejs-production.up.railway.app/api',
  USERS: '/users',
  NOTICES: '/notices',
  FRIENDS: '/ours_friends',
  FAVORITES: '/favorites',
  OWNADS: '/my_notices',
  NEWS: '/news',
  PETS: '/pets',
  QUERY: 'query=',
  SALE: '?category=sale',
  FOUND: '?category=lostFound',
  HANDS: '?category=inGoodHands',
  REGISTRATION: 'registration',
  LOGIN: '/login',
  LOGOUT: '/logout',
  CURRENT: '/current',
  PROFILE: '/profile',
  AVATAR: '/avatar',
  FORGOT: '/forgot_password',
};
